import 'dotenv/config'
import { Pool } from 'pg'
import { PrismaPg } from '@prisma/adapter-pg'
import { PrismaClient } from '../src/generated/prisma'

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const adapter = new PrismaPg(pool)
const prisma = new PrismaClient({ adapter })

interface CollegeSeed {
  name: string
  city: string
  state: string
  type: string
  nirfRank: number
  nirfScore: number
  fees: number
  rating: number
  established: number
  description: string
  website: string
  field: string
  courses: { name: string; duration: number; seats: number; fees: number }[]
  placement: {
    avgPackage: number
    highestPackage: number
    placementPercent: number
    topRecruiters: string
  }
  predictorData: { exam: string; category: string; openingRank: number; closingRank: number }[]
}

const colleges: CollegeSeed[] = [
  {
    name: 'IIT Madras',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Government',
    nirfRank: 1,
    nirfScore: 91.72,
    fees: 225000,
    rating: 4.8,
    established: 1959,
    description: 'Premier engineering institute consistently ranked #1 in India by NIRF.',
    website: 'https://www.iitm.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 120, fees: 225000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 90, fees: 225000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 100, fees: 225000 },
      { name: 'M.Tech Artificial Intelligence', duration: 2, seats: 50, fees: 250000 },
    ],
    placement: {
      avgPackage: 32,
      highestPackage: 150,
      placementPercent: 95,
      topRecruiters: 'Google,Microsoft,Apple,Amazon,Goldman Sachs',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 1, closingRank: 500 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 100, closingRank: 800 },
      { exam: 'JEE_ADVANCED', category: 'SC', openingRank: 300, closingRank: 1500 },
    ],
  },
  {
    name: 'IIT Delhi',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Government',
    nirfRank: 2,
    nirfScore: 88.08,
    fees: 220000,
    rating: 4.8,
    established: 1961,
    description: 'Top-tier IIT located in the capital with world-class research facilities.',
    website: 'https://home.iitd.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 100, fees: 220000 },
      { name: 'B.Tech Electronics & Communication', duration: 4, seats: 80, fees: 220000 },
      { name: 'B.Tech Chemical Engineering', duration: 4, seats: 70, fees: 220000 },
      { name: 'M.Tech Machine Learning', duration: 2, seats: 40, fees: 240000 },
    ],
    placement: {
      avgPackage: 30,
      highestPackage: 130,
      placementPercent: 94,
      topRecruiters: 'Facebook,Uber,Adobe,McKinsey,Qualcomm',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 10, closingRank: 600 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 150, closingRank: 1000 },
      { exam: 'JEE_ADVANCED', category: 'SC', openingRank: 400, closingRank: 1800 },
    ],
  },
  {
    name: 'IIT Bombay',
    city: 'Mumbai',
    state: 'Maharashtra',
    type: 'Government',
    nirfRank: 3,
    nirfScore: 85.61,
    fees: 230000,
    rating: 4.8,
    established: 1958,
    description: 'Premier IIT in Mumbai, renowned for placements and research.',
    website: 'https://www.iitb.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 110, fees: 230000 },
      { name: 'B.Tech Aerospace Engineering', duration: 4, seats: 60, fees: 230000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 80, fees: 230000 },
      { name: 'M.Tech Data Science', duration: 2, seats: 45, fees: 250000 },
    ],
    placement: {
      avgPackage: 33,
      highestPackage: 140,
      placementPercent: 96,
      topRecruiters: 'Google,Microsoft,DE Shaw,Quadeye,Tower Research',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 5, closingRank: 550 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 120, closingRank: 900 },
      { exam: 'JEE_ADVANCED', category: 'EWS', openingRank: 200, closingRank: 1200 },
    ],
  },
  {
    name: 'IIT Kanpur',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    type: 'Government',
    nirfRank: 4,
    nirfScore: 83.97,
    fees: 215000,
    rating: 4.7,
    established: 1959,
    description: 'Known for strong CS and engineering programs with excellent research.',
    website: 'https://www.iitk.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 90, fees: 215000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 85, fees: 215000 },
      { name: 'B.Tech Physics', duration: 4, seats: 50, fees: 215000 },
    ],
    placement: {
      avgPackage: 28,
      highestPackage: 120,
      placementPercent: 92,
      topRecruiters: 'Amazon,Samsung,Oracle,KPMG,Infosys',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 20, closingRank: 700 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 200, closingRank: 1100 },
      { exam: 'JEE_ADVANCED', category: 'SC', openingRank: 500, closingRank: 2000 },
    ],
  },
  {
    name: 'IIT Kharagpur',
    city: 'Kharagpur',
    state: 'West Bengal',
    type: 'Government',
    nirfRank: 5,
    nirfScore: 82.54,
    fees: 210000,
    rating: 4.7,
    established: 1951,
    description: 'The oldest IIT with the largest campus and broadest program offering.',
    website: 'https://www.iitkgp.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 120, fees: 210000 },
      { name: 'B.Tech Mining Engineering', duration: 4, seats: 50, fees: 210000 },
      { name: 'B.Tech Ocean Engineering', duration: 4, seats: 40, fees: 210000 },
      { name: 'M.Tech VLSI Design', duration: 2, seats: 35, fees: 235000 },
    ],
    placement: {
      avgPackage: 27,
      highestPackage: 115,
      placementPercent: 91,
      topRecruiters: 'Tata Steel,Infosys,Wipro,Cognizant,TCS',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 30, closingRank: 900 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 250, closingRank: 1400 },
      { exam: 'JEE_ADVANCED', category: 'ST', openingRank: 800, closingRank: 3000 },
    ],
  },
  {
    name: 'IIT Roorkee',
    city: 'Roorkee',
    state: 'Uttarakhand',
    type: 'Government',
    nirfRank: 6,
    nirfScore: 81.13,
    fees: 212000,
    rating: 4.6,
    established: 1847,
    description: "Asia's oldest technical university with exceptional civil engineering heritage.",
    website: 'https://www.iitr.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 100, fees: 212000 },
      { name: 'B.Tech Computer Science', duration: 4, seats: 80, fees: 212000 },
      { name: 'B.Tech Biotechnology', duration: 4, seats: 50, fees: 212000 },
    ],
    placement: {
      avgPackage: 25,
      highestPackage: 100,
      placementPercent: 90,
      topRecruiters: 'L&T,Accenture,Deloitte,IBM,Schlumberger',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 50, closingRank: 1200 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 300, closingRank: 1800 },
      { exam: 'JEE_ADVANCED', category: 'SC', openingRank: 700, closingRank: 3500 },
    ],
  },
  {
    name: 'IIT Guwahati',
    city: 'Guwahati',
    state: 'Assam',
    type: 'Government',
    nirfRank: 7,
    nirfScore: 78.32,
    fees: 208000,
    rating: 4.5,
    established: 1994,
    description: 'Leading IIT in Northeast India with strong placement records.',
    website: 'https://www.iitg.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 80, fees: 208000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 70, fees: 208000 },
      { name: 'B.Tech Design', duration: 4, seats: 30, fees: 208000 },
    ],
    placement: {
      avgPackage: 22,
      highestPackage: 90,
      placementPercent: 88,
      topRecruiters: 'Flipkart,PayTM,Ola,Zomato,Vedanta',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 100, closingRank: 2000 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 500, closingRank: 3000 },
      { exam: 'JEE_ADVANCED', category: 'SC', openingRank: 1000, closingRank: 5000 },
    ],
  },
  {
    name: 'IIT Hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Government',
    nirfRank: 8,
    nirfScore: 74.91,
    fees: 205000,
    rating: 4.5,
    established: 2008,
    description: 'Young IIT with cutting-edge research in AI, ML and interdisciplinary fields.',
    website: 'https://www.iith.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 70, fees: 205000 },
      { name: 'B.Tech Artificial Intelligence', duration: 4, seats: 40, fees: 205000 },
      { name: 'B.Tech Materials Science', duration: 4, seats: 35, fees: 205000 },
    ],
    placement: {
      avgPackage: 20,
      highestPackage: 80,
      placementPercent: 87,
      topRecruiters: 'Microsoft,Google,Samsung Research,Bosch,Qualcomm',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 150, closingRank: 2500 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 600, closingRank: 4000 },
      { exam: 'JEE_ADVANCED', category: 'EWS', openingRank: 400, closingRank: 3200 },
    ],
  },
  {
    name: 'NIT Trichy',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    type: 'Government',
    nirfRank: 9,
    nirfScore: 72.14,
    fees: 165000,
    rating: 4.4,
    established: 1964,
    description: 'Top-ranked NIT with outstanding placements and academic excellence.',
    website: 'https://www.nitt.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 120, fees: 165000 },
      { name: 'B.Tech Electronics & Communication', duration: 4, seats: 100, fees: 165000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 90, fees: 165000 },
    ],
    placement: {
      avgPackage: 13,
      highestPackage: 55,
      placementPercent: 88,
      topRecruiters: 'TCS,Infosys,Cognizant,Wipro,Capgemini',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 4000, closingRank: 12000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 6000, closingRank: 18000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 10000, closingRank: 30000 },
    ],
  },
  {
    name: 'Jadavpur University',
    city: 'Kolkata',
    state: 'West Bengal',
    type: 'Government',
    nirfRank: 10,
    nirfScore: 70.82,
    fees: 50000,
    rating: 4.3,
    established: 1955,
    description: 'Premier state university renowned for engineering and research.',
    website: 'https://www.jadavpuruniversity.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 80, fees: 50000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 75, fees: 50000 },
      { name: 'B.Tech Electronics', duration: 4, seats: 70, fees: 50000 },
    ],
    placement: {
      avgPackage: 12,
      highestPackage: 48,
      placementPercent: 82,
      topRecruiters: 'TCS,Wipro,HCL,Tech Mahindra,IBM',
    },
    predictorData: [
      { exam: 'WBJEE', category: 'GENERAL', openingRank: 100, closingRank: 2000 },
      { exam: 'WBJEE', category: 'OBC', openingRank: 500, closingRank: 4000 },
      { exam: 'WBJEE', category: 'SC', openingRank: 1000, closingRank: 6000 },
    ],
  },
  {
    name: 'IIT BHU Varanasi',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    type: 'Government',
    nirfRank: 11,
    nirfScore: 68.49,
    fees: 210000,
    rating: 4.4,
    established: 1919,
    description: 'Historic engineering institute located within Banaras Hindu University.',
    website: 'https://iitbhu.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 70, fees: 210000 },
      { name: 'B.Tech Metallurgical Engineering', duration: 4, seats: 60, fees: 210000 },
      { name: 'B.Tech Mining Engineering', duration: 4, seats: 55, fees: 210000 },
    ],
    placement: {
      avgPackage: 19,
      highestPackage: 75,
      placementPercent: 86,
      topRecruiters: 'SAIL,Coal India,TCS,Infosys,HDFC Bank',
    },
    predictorData: [
      { exam: 'JEE_ADVANCED', category: 'GENERAL', openingRank: 200, closingRank: 4000 },
      { exam: 'JEE_ADVANCED', category: 'OBC', openingRank: 700, closingRank: 6000 },
      { exam: 'JEE_ADVANCED', category: 'SC', openingRank: 1500, closingRank: 9000 },
    ],
  },
  {
    name: 'Sardar Vallabhbhai NIT Surat',
    city: 'Surat',
    state: 'Gujarat',
    type: 'Government',
    nirfRank: 12,
    nirfScore: 66.21,
    fees: 160000,
    rating: 4.2,
    established: 1961,
    description: 'Top NIT in Gujarat with strong industry connections and placements.',
    website: 'https://www.svnit.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 90, fees: 160000 },
      { name: 'B.Tech Chemical Engineering', duration: 4, seats: 80, fees: 160000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 75, fees: 160000 },
    ],
    placement: {
      avgPackage: 11,
      highestPackage: 42,
      placementPercent: 83,
      topRecruiters: 'Reliance,L&T,Adani,TCS,Wipro',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 6000, closingRank: 20000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 9000, closingRank: 30000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 15000, closingRank: 45000 },
    ],
  },
  {
    name: 'NIT Warangal',
    city: 'Warangal',
    state: 'Telangana',
    type: 'Government',
    nirfRank: 13,
    nirfScore: 65.87,
    fees: 162000,
    rating: 4.3,
    established: 1959,
    description: 'One of the top NITs with excellent technical education and placements.',
    website: 'https://www.nitw.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 100, fees: 162000 },
      { name: 'B.Tech Electronics & Communication', duration: 4, seats: 85, fees: 162000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 90, fees: 162000 },
    ],
    placement: {
      avgPackage: 12,
      highestPackage: 50,
      placementPercent: 85,
      topRecruiters: 'TCS,Infosys,Wipro,HCL,Cognizant',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 5000, closingRank: 18000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 8000, closingRank: 26000 },
      { exam: 'JEE_MAIN', category: 'EWS', openingRank: 7000, closingRank: 22000 },
    ],
  },
  {
    name: 'BITS Pilani',
    city: 'Pilani',
    state: 'Rajasthan',
    type: 'Deemed',
    nirfRank: 14,
    nirfScore: 64.33,
    fees: 420000,
    rating: 4.5,
    established: 1964,
    description: 'Top private deemed university with industry-oriented curriculum and practice school.',
    website: 'https://www.bits-pilani.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 100, fees: 420000 },
      { name: 'B.Tech Electronics & Instrumentation', duration: 4, seats: 80, fees: 420000 },
      { name: 'B.Tech Chemical Engineering', duration: 4, seats: 70, fees: 420000 },
      { name: 'M.Tech Software Systems', duration: 2, seats: 40, fees: 440000 },
    ],
    placement: {
      avgPackage: 14,
      highestPackage: 60,
      placementPercent: 85,
      topRecruiters: 'Google,Amazon,Goldman Sachs,Morgan Stanley,Salesforce',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 2000, closingRank: 10000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 4000, closingRank: 15000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 8000, closingRank: 25000 },
    ],
  },
  {
    name: 'VIT Vellore',
    city: 'Vellore',
    state: 'Tamil Nadu',
    type: 'Deemed',
    nirfRank: 15,
    nirfScore: 61.27,
    fees: 350000,
    rating: 4.1,
    established: 1984,
    description: 'Large private university with strong industry linkages and global partnerships.',
    website: 'https://vit.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 500, fees: 350000 },
      { name: 'B.Tech Information Technology', duration: 4, seats: 300, fees: 350000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 250, fees: 350000 },
    ],
    placement: {
      avgPackage: 7,
      highestPackage: 35,
      placementPercent: 75,
      topRecruiters: 'TCS,Wipro,Infosys,Accenture,Capgemini',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 20000, closingRank: 80000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 30000, closingRank: 100000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 40000, closingRank: 120000 },
    ],
  },
  {
    name: 'SRM Institute Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Deemed',
    nirfRank: 16,
    nirfScore: 58.94,
    fees: 280000,
    rating: 3.9,
    established: 1985,
    description: 'Large private university with extensive industry connections in Chennai.',
    website: 'https://www.srmist.edu.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 600, fees: 280000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 400, fees: 280000 },
      { name: 'B.Tech Biomedical Engineering', duration: 4, seats: 150, fees: 280000 },
    ],
    placement: {
      avgPackage: 6,
      highestPackage: 28,
      placementPercent: 72,
      topRecruiters: 'TCS,Wipro,Cognizant,HCL,Tech Mahindra',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 40000, closingRank: 120000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 60000, closingRank: 160000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 70000, closingRank: 200000 },
    ],
  },
  {
    name: 'Amrita Vishwa Vidyapeetham',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    type: 'Deemed',
    nirfRank: 17,
    nirfScore: 57.43,
    fees: 200000,
    rating: 4.0,
    established: 1994,
    description: 'Multi-campus deemed university with strong research output and placements.',
    website: 'https://www.amrita.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 300, fees: 200000 },
      { name: 'B.Tech Cybersecurity', duration: 4, seats: 100, fees: 200000 },
      { name: 'B.Tech Robotics', duration: 4, seats: 80, fees: 200000 },
    ],
    placement: {
      avgPackage: 7,
      highestPackage: 30,
      placementPercent: 74,
      topRecruiters: 'Infosys,TCS,Wipro,Bosch,Zoho',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 35000, closingRank: 100000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 50000, closingRank: 130000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 65000, closingRank: 170000 },
    ],
  },
  {
    name: 'Thapar Institute Patiala',
    city: 'Patiala',
    state: 'Punjab',
    type: 'Deemed',
    nirfRank: 18,
    nirfScore: 55.89,
    fees: 380000,
    rating: 4.2,
    established: 1956,
    description: 'Reputed private deemed university in Punjab with excellent engineering programs.',
    website: 'https://www.thapar.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 200, fees: 380000 },
      { name: 'B.Tech Electronics & Communication', duration: 4, seats: 150, fees: 380000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 120, fees: 380000 },
    ],
    placement: {
      avgPackage: 9,
      highestPackage: 38,
      placementPercent: 78,
      topRecruiters: 'Samsung,LG,Maruti,BPCL,Infosys',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 15000, closingRank: 55000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 22000, closingRank: 75000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 30000, closingRank: 95000 },
    ],
  },
  {
    name: 'Manipal Institute of Technology',
    city: 'Manipal',
    state: 'Karnataka',
    type: 'Deemed',
    nirfRank: 19,
    nirfScore: 54.72,
    fees: 390000,
    rating: 4.1,
    established: 1957,
    description: 'Well-known private university with diverse engineering programs and global alumni.',
    website: 'https://manipal.edu/mit',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 250, fees: 390000 },
      { name: 'B.Tech Information Technology', duration: 4, seats: 200, fees: 390000 },
      { name: 'B.Tech Mechatronics', duration: 4, seats: 80, fees: 390000 },
    ],
    placement: {
      avgPackage: 8,
      highestPackage: 32,
      placementPercent: 76,
      topRecruiters: 'Infosys,TCS,Wipro,Capgemini,L&T',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 18000, closingRank: 65000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 28000, closingRank: 90000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 40000, closingRank: 110000 },
    ],
  },
  {
    name: 'IIIT Hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    type: 'Deemed',
    nirfRank: 20,
    nirfScore: 53.41,
    fees: 320000,
    rating: 4.4,
    established: 1998,
    description: 'Premier IIIT specializing in computer science and research with top placements.',
    website: 'https://www.iiit.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 120, fees: 320000 },
      { name: 'B.Tech Electronics & Communication', duration: 4, seats: 80, fees: 320000 },
      { name: 'M.Tech Computational Linguistics', duration: 2, seats: 30, fees: 340000 },
    ],
    placement: {
      avgPackage: 18,
      highestPackage: 70,
      placementPercent: 90,
      topRecruiters: 'Google,Microsoft,Amazon,Goldman Sachs,Facebook',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 3000, closingRank: 12000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 5000, closingRank: 18000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 8000, closingRank: 28000 },
    ],
  },
  {
    name: 'NIT Calicut',
    city: 'Kozhikode',
    state: 'Kerala',
    type: 'Government',
    nirfRank: 21,
    nirfScore: 52.18,
    fees: 158000,
    rating: 4.2,
    established: 1961,
    description: 'Premier NIT in Kerala with strong technical programs and industry placements.',
    website: 'https://www.nitc.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 90, fees: 158000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 80, fees: 158000 },
      { name: 'B.Tech Architecture', duration: 5, seats: 40, fees: 158000 },
    ],
    placement: {
      avgPackage: 10,
      highestPackage: 40,
      placementPercent: 80,
      topRecruiters: 'TCS,Infosys,UST Global,KPMG,Deloitte',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 7000, closingRank: 22000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 10000, closingRank: 32000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 16000, closingRank: 48000 },
    ],
  },
  {
    name: 'NIT Rourkela',
    city: 'Rourkela',
    state: 'Odisha',
    type: 'Government',
    nirfRank: 22,
    nirfScore: 51.64,
    fees: 155000,
    rating: 4.1,
    established: 1961,
    description: 'Top NIT in Odisha with strong metallurgy and mechanical engineering programs.',
    website: 'https://www.nitrkl.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 85, fees: 155000 },
      { name: 'B.Tech Metallurgical Engineering', duration: 4, seats: 70, fees: 155000 },
      { name: 'B.Tech Chemical Engineering', duration: 4, seats: 65, fees: 155000 },
    ],
    placement: {
      avgPackage: 9,
      highestPackage: 36,
      placementPercent: 78,
      topRecruiters: 'TATA Steel,SAIL,Infosys,TCS,Wipro',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 8000, closingRank: 25000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 12000, closingRank: 36000 },
      { exam: 'JEE_MAIN', category: 'ST', openingRank: 20000, closingRank: 55000 },
    ],
  },
  {
    name: 'NIT Karnataka Surathkal',
    city: 'Surathkal',
    state: 'Karnataka',
    type: 'Government',
    nirfRank: 23,
    nirfScore: 50.97,
    fees: 160000,
    rating: 4.2,
    established: 1960,
    description: 'Reputed NIT with excellent placement records and coastal campus in Karnataka.',
    website: 'https://www.nitk.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 90, fees: 160000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 80, fees: 160000 },
      { name: 'B.Tech Mining Engineering', duration: 4, seats: 60, fees: 160000 },
    ],
    placement: {
      avgPackage: 11,
      highestPackage: 44,
      placementPercent: 82,
      topRecruiters: 'Infosys,TCS,Amazon,Flipkart,Goldman Sachs',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 6500, closingRank: 21000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 9500, closingRank: 30000 },
      { exam: 'JEE_MAIN', category: 'EWS', openingRank: 8000, closingRank: 25000 },
    ],
  },
  {
    name: 'NIT Durgapur',
    city: 'Durgapur',
    state: 'West Bengal',
    type: 'Government',
    nirfRank: 24,
    nirfScore: 49.38,
    fees: 152000,
    rating: 4.0,
    established: 1960,
    description: 'Well-established NIT in West Bengal with strong engineering programs.',
    website: 'https://www.nitdgp.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 80, fees: 152000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 75, fees: 152000 },
      { name: 'B.Tech Biotechnology', duration: 4, seats: 50, fees: 152000 },
    ],
    placement: {
      avgPackage: 8,
      highestPackage: 32,
      placementPercent: 76,
      topRecruiters: 'TCS,Infosys,Wipro,IBM,Accenture',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 10000, closingRank: 30000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 15000, closingRank: 42000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 20000, closingRank: 55000 },
    ],
  },
  {
    name: 'IIIT Allahabad',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    type: 'Government',
    nirfRank: 25,
    nirfScore: 48.71,
    fees: 170000,
    rating: 4.1,
    established: 1999,
    description: 'Premier IIIT with focus on IT and software engineering with solid placements.',
    website: 'https://www.iiita.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Information Technology', duration: 4, seats: 150, fees: 170000 },
      { name: 'B.Tech Electronics & Communication', duration: 4, seats: 100, fees: 170000 },
      { name: 'M.Tech Software Engineering', duration: 2, seats: 50, fees: 190000 },
    ],
    placement: {
      avgPackage: 12,
      highestPackage: 48,
      placementPercent: 84,
      topRecruiters: 'Microsoft,Samsung,Walmart Labs,Juspay,Adobe',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 5000, closingRank: 16000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 8000, closingRank: 24000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 12000, closingRank: 35000 },
    ],
  },
  {
    name: 'Delhi Technological University',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Government',
    nirfRank: 26,
    nirfScore: 47.92,
    fees: 100000,
    rating: 4.0,
    established: 1941,
    description: 'Top state engineering university in Delhi with excellent placement records.',
    website: 'https://dtu.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 180, fees: 100000 },
      { name: 'B.Tech Software Engineering', duration: 4, seats: 120, fees: 100000 },
      { name: 'B.Tech Environmental Engineering', duration: 4, seats: 60, fees: 100000 },
    ],
    placement: {
      avgPackage: 11,
      highestPackage: 45,
      placementPercent: 80,
      topRecruiters: 'Amazon,Microsoft,Paytm,Zomato,Walmart',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 3500, closingRank: 14000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 6000, closingRank: 20000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 9000, closingRank: 28000 },
    ],
  },
  {
    name: 'Netaji Subhas University of Technology',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Government',
    nirfRank: 27,
    nirfScore: 46.15,
    fees: 95000,
    rating: 3.9,
    established: 1983,
    description: 'Delhi state engineering university formerly known as NSIT with good placements.',
    website: 'https://www.nsut.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Engineering', duration: 4, seats: 120, fees: 95000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 100, fees: 95000 },
      { name: 'B.Tech Instrumentation & Control', duration: 4, seats: 60, fees: 95000 },
    ],
    placement: {
      avgPackage: 9,
      highestPackage: 38,
      placementPercent: 76,
      topRecruiters: 'Infosys,TCS,Amazon,Snapdeal,Paytm',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 4000, closingRank: 16000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 7000, closingRank: 23000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 10000, closingRank: 30000 },
    ],
  },
  {
    name: 'PEC Chandigarh',
    city: 'Chandigarh',
    state: 'Punjab',
    type: 'Government',
    nirfRank: 28,
    nirfScore: 44.88,
    fees: 85000,
    rating: 3.8,
    established: 1921,
    description: 'Oldest engineering college in Northern India with strong alumni network.',
    website: 'https://pec.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 80, fees: 85000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 90, fees: 85000 },
      { name: 'B.Tech Aerospace Engineering', duration: 4, seats: 40, fees: 85000 },
    ],
    placement: {
      avgPackage: 8,
      highestPackage: 30,
      placementPercent: 74,
      topRecruiters: 'DRDO,HAL,Infosys,TCS,Maruti',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 8000, closingRank: 26000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 12000, closingRank: 36000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 18000, closingRank: 50000 },
    ],
  },
  {
    name: 'BIT Mesra',
    city: 'Ranchi',
    state: 'Jharkhand',
    type: 'Deemed',
    nirfRank: 29,
    nirfScore: 43.52,
    fees: 240000,
    rating: 3.9,
    established: 1955,
    description: 'Well-reputed private deemed university in Jharkhand with decent placements.',
    website: 'https://www.bitmesra.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 120, fees: 240000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 100, fees: 240000 },
      { name: 'B.Tech Production Engineering', duration: 4, seats: 70, fees: 240000 },
    ],
    placement: {
      avgPackage: 7,
      highestPackage: 28,
      placementPercent: 70,
      topRecruiters: 'Infosys,TCS,Wipro,SAIL,Coal India',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 15000, closingRank: 50000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 22000, closingRank: 68000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 30000, closingRank: 85000 },
    ],
  },
  {
    name: 'MNNIT Allahabad',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    type: 'Government',
    nirfRank: 30,
    nirfScore: 42.87,
    fees: 157000,
    rating: 4.0,
    established: 1961,
    description: 'Motilal Nehru NIT with strong engineering programs in Uttar Pradesh.',
    website: 'https://www.mnnit.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 85, fees: 157000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 80, fees: 157000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 75, fees: 157000 },
    ],
    placement: {
      avgPackage: 8,
      highestPackage: 33,
      placementPercent: 77,
      topRecruiters: 'TCS,Infosys,BPCL,NTPC,Wipro',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 9000, closingRank: 28000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 13000, closingRank: 40000 },
      { exam: 'JEE_MAIN', category: 'EWS', openingRank: 11000, closingRank: 34000 },
    ],
  },
  {
    name: 'NIT Jamshedpur',
    city: 'Jamshedpur',
    state: 'Jharkhand',
    type: 'Government',
    nirfRank: 31,
    nirfScore: 41.24,
    fees: 153000,
    rating: 3.9,
    established: 1960,
    description: 'NIT located in Jamshedpur with strong industry ties especially to TATA group.',
    website: 'https://www.nitjsr.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 80, fees: 153000 },
      { name: 'B.Tech Metallurgical Engineering', duration: 4, seats: 65, fees: 153000 },
      { name: 'B.Tech Production Engineering', duration: 4, seats: 70, fees: 153000 },
    ],
    placement: {
      avgPackage: 7,
      highestPackage: 28,
      placementPercent: 72,
      topRecruiters: 'Tata Steel,Tata Motors,Infosys,TCS,Wipro',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 12000, closingRank: 38000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 18000, closingRank: 52000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 24000, closingRank: 65000 },
    ],
  },
  {
    name: 'NIT Patna',
    city: 'Patna',
    state: 'Bihar',
    type: 'Government',
    nirfRank: 32,
    nirfScore: 40.18,
    fees: 150000,
    rating: 3.8,
    established: 1886,
    description: 'One of the oldest NIT in Bihar offering diverse engineering programs.',
    website: 'https://www.nitp.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 75, fees: 150000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 80, fees: 150000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 70, fees: 150000 },
    ],
    placement: {
      avgPackage: 6,
      highestPackage: 24,
      placementPercent: 68,
      topRecruiters: 'TCS,Wipro,Infosys,HCL,Persistent',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 15000, closingRank: 45000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 22000, closingRank: 60000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 28000, closingRank: 75000 },
    ],
  },
  {
    name: 'Jamia Millia Islamia',
    city: 'New Delhi',
    state: 'Delhi',
    type: 'Government',
    nirfRank: 33,
    nirfScore: 39.64,
    fees: 40000,
    rating: 3.8,
    established: 1920,
    description: 'Central university in Delhi with strong engineering and technical programs.',
    website: 'https://www.jmi.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Engineering', duration: 4, seats: 70, fees: 40000 },
      { name: 'B.Tech Electronics & Communication', duration: 4, seats: 65, fees: 40000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 60, fees: 40000 },
    ],
    placement: {
      avgPackage: 7,
      highestPackage: 26,
      placementPercent: 70,
      topRecruiters: 'TCS,Infosys,Wipro,HCL,IBM',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 10000, closingRank: 35000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 15000, closingRank: 48000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 20000, closingRank: 60000 },
    ],
  },
  {
    name: 'Anna University Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    type: 'Government',
    nirfRank: 34,
    nirfScore: 38.92,
    fees: 45000,
    rating: 3.9,
    established: 1978,
    description: 'Premier state technical university in Tamil Nadu with large alumni network.',
    website: 'https://www.annauniv.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 120, fees: 45000 },
      { name: 'B.Tech Information Technology', duration: 4, seats: 90, fees: 45000 },
      { name: 'M.Tech Software Engineering', duration: 2, seats: 40, fees: 55000 },
    ],
    placement: {
      avgPackage: 6,
      highestPackage: 22,
      placementPercent: 68,
      topRecruiters: 'TCS,Infosys,CTS,HCL,Zoho',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 12000, closingRank: 40000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 18000, closingRank: 55000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 25000, closingRank: 70000 },
    ],
  },
  {
    name: 'PSG College of Technology',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    type: 'Private',
    nirfRank: 35,
    nirfScore: 37.81,
    fees: 180000,
    rating: 4.0,
    established: 1951,
    description: 'Reputed autonomous institution in Coimbatore with strong industry collaborations.',
    website: 'https://www.psgtech.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 120, fees: 180000 },
      { name: 'B.Tech Mechatronics', duration: 4, seats: 80, fees: 180000 },
      { name: 'B.Tech Production Engineering', duration: 4, seats: 75, fees: 180000 },
    ],
    placement: {
      avgPackage: 6,
      highestPackage: 24,
      placementPercent: 73,
      topRecruiters: 'Infosys,Wipro,CTS,TCS,Bosch',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 25000, closingRank: 70000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 35000, closingRank: 90000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 45000, closingRank: 110000 },
    ],
  },
  {
    name: 'Coimbatore Institute of Technology',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    type: 'Private',
    nirfRank: 36,
    nirfScore: 36.54,
    fees: 150000,
    rating: 3.8,
    established: 1956,
    description: 'Autonomous institution in Coimbatore offering quality engineering education.',
    website: 'https://www.cit.edu.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 100, fees: 150000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 90, fees: 150000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 85, fees: 150000 },
    ],
    placement: {
      avgPackage: 5,
      highestPackage: 20,
      placementPercent: 65,
      topRecruiters: 'TCS,Infosys,CTS,HCL,Wipro',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 40000, closingRank: 100000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 55000, closingRank: 130000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 65000, closingRank: 160000 },
    ],
  },
  {
    name: 'Amity University Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    type: 'Private',
    nirfRank: 37,
    nirfScore: 35.42,
    fees: 280000,
    rating: 3.7,
    established: 2005,
    description: 'Large private university in NCR with diverse programs and industry tie-ups.',
    website: 'https://www.amity.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 400, fees: 280000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 250, fees: 280000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 150, fees: 280000 },
    ],
    placement: {
      avgPackage: 5,
      highestPackage: 18,
      placementPercent: 62,
      topRecruiters: 'TCS,Infosys,Wipro,KPMG,Deloitte',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 50000, closingRank: 150000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 70000, closingRank: 190000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 90000, closingRank: 230000 },
    ],
  },
  {
    name: 'LPU Jalandhar',
    city: 'Jalandhar',
    state: 'Punjab',
    type: 'Private',
    nirfRank: 38,
    nirfScore: 34.27,
    fees: 200000,
    rating: 3.6,
    established: 2005,
    description: 'Large private university in Punjab known for diverse programs and campus life.',
    website: 'https://www.lpu.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 600, fees: 200000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 400, fees: 200000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 300, fees: 200000 },
    ],
    placement: {
      avgPackage: 4,
      highestPackage: 16,
      placementPercent: 60,
      topRecruiters: 'TCS,Wipro,Infosys,HCL,Capgemini',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 60000, closingRank: 180000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 80000, closingRank: 220000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 100000, closingRank: 260000 },
    ],
  },
  {
    name: 'Chandigarh University',
    city: 'Chandigarh',
    state: 'Punjab',
    type: 'Private',
    nirfRank: 39,
    nirfScore: 33.18,
    fees: 220000,
    rating: 3.7,
    established: 2012,
    description: 'Growing private university in Punjab with strong startup culture and placements.',
    website: 'https://www.cuchd.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 500, fees: 220000 },
      { name: 'B.Tech Cybersecurity', duration: 4, seats: 200, fees: 220000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 300, fees: 220000 },
    ],
    placement: {
      avgPackage: 5,
      highestPackage: 20,
      placementPercent: 65,
      topRecruiters: 'Infosys,TCS,Wipro,Amazon,Accenture',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 55000, closingRank: 160000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 75000, closingRank: 200000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 95000, closingRank: 240000 },
    ],
  },
  {
    name: 'UPES Dehradun',
    city: 'Dehradun',
    state: 'Uttarakhand',
    type: 'Private',
    nirfRank: 40,
    nirfScore: 32.04,
    fees: 250000,
    rating: 3.7,
    established: 2003,
    description: 'Sector-specific university specializing in energy, oil, and gas engineering.',
    website: 'https://www.upes.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 200, fees: 250000 },
      { name: 'B.Tech Petroleum Engineering', duration: 4, seats: 150, fees: 250000 },
      { name: 'B.Tech Fire & Safety', duration: 4, seats: 80, fees: 250000 },
    ],
    placement: {
      avgPackage: 6,
      highestPackage: 22,
      placementPercent: 68,
      topRecruiters: 'ONGC,HPCL,BPCL,Schlumberger,Infosys',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 45000, closingRank: 130000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 60000, closingRank: 165000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 75000, closingRank: 200000 },
    ],
  },
  {
    name: 'Symbiosis Institute of Technology Pune',
    city: 'Pune',
    state: 'Maharashtra',
    type: 'Deemed',
    nirfRank: 41,
    nirfScore: 31.27,
    fees: 260000,
    rating: 3.8,
    established: 2008,
    description: 'Technology institute under Symbiosis International University in Pune.',
    website: 'https://www.sitpune.edu.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 180, fees: 260000 },
      { name: 'B.Tech IT', duration: 4, seats: 120, fees: 260000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 90, fees: 260000 },
    ],
    placement: {
      avgPackage: 6,
      highestPackage: 22,
      placementPercent: 70,
      topRecruiters: 'TCS,Infosys,Wipro,Capgemini,Persistent',
    },
    predictorData: [
      { exam: 'MHT_CET', category: 'GENERAL', openingRank: 5000, closingRank: 20000 },
      { exam: 'MHT_CET', category: 'OBC', openingRank: 8000, closingRank: 30000 },
      { exam: 'MHT_CET', category: 'SC', openingRank: 12000, closingRank: 45000 },
    ],
  },
  {
    name: 'MIT Pune',
    city: 'Pune',
    state: 'Maharashtra',
    type: 'Private',
    nirfRank: 42,
    nirfScore: 30.54,
    fees: 180000,
    rating: 3.8,
    established: 1983,
    description: 'MIT College of Engineering Pune, one of the oldest private institutes in Maharashtra.',
    website: 'https://www.mitcoe.edu.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Engineering', duration: 4, seats: 180, fees: 180000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 120, fees: 180000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 100, fees: 180000 },
    ],
    placement: {
      avgPackage: 5,
      highestPackage: 20,
      placementPercent: 68,
      topRecruiters: 'TCS,Wipro,Infosys,Persistent,Cognizant',
    },
    predictorData: [
      { exam: 'MHT_CET', category: 'GENERAL', openingRank: 8000, closingRank: 28000 },
      { exam: 'MHT_CET', category: 'OBC', openingRank: 12000, closingRank: 40000 },
      { exam: 'MHT_CET', category: 'SC', openingRank: 18000, closingRank: 55000 },
    ],
  },
  {
    name: 'KIIT Bhubaneswar',
    city: 'Bhubaneswar',
    state: 'Odisha',
    type: 'Deemed',
    nirfRank: 43,
    nirfScore: 29.87,
    fees: 300000,
    rating: 4.0,
    established: 1992,
    description: 'KIIT Deemed University with strong placements and modern infrastructure.',
    website: 'https://kiit.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 400, fees: 300000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 250, fees: 300000 },
      { name: 'B.Tech Civil Engineering', duration: 4, seats: 150, fees: 300000 },
    ],
    placement: {
      avgPackage: 7,
      highestPackage: 30,
      placementPercent: 74,
      topRecruiters: 'TCS,Infosys,Wipro,Capgemini,Amazon',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 30000, closingRank: 90000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 45000, closingRank: 120000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 60000, closingRank: 150000 },
    ],
  },
  {
    name: 'SASTRA Deemed University',
    city: 'Thanjavur',
    state: 'Tamil Nadu',
    type: 'Deemed',
    nirfRank: 44,
    nirfScore: 28.94,
    fees: 160000,
    rating: 3.9,
    established: 1984,
    description: 'Reputed deemed university in Tamil Nadu with quality academics and placements.',
    website: 'https://www.sastra.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 200, fees: 160000 },
      { name: 'B.Tech Bioinformatics', duration: 4, seats: 80, fees: 160000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 120, fees: 160000 },
    ],
    placement: {
      avgPackage: 5,
      highestPackage: 18,
      placementPercent: 66,
      topRecruiters: 'TCS,Wipro,Infosys,Zoho,HCL',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 35000, closingRank: 100000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 50000, closingRank: 130000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 65000, closingRank: 165000 },
    ],
  },
  {
    name: 'VIT Bhopal',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    type: 'Private',
    nirfRank: 45,
    nirfScore: 27.83,
    fees: 280000,
    rating: 3.7,
    established: 2017,
    description: 'VIT group campus in Bhopal offering engineering education with VIT brand value.',
    website: 'https://vitbhopal.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 300, fees: 280000 },
      { name: 'B.Tech AI & Machine Learning', duration: 4, seats: 150, fees: 280000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 180, fees: 280000 },
    ],
    placement: {
      avgPackage: 5,
      highestPackage: 20,
      placementPercent: 63,
      topRecruiters: 'TCS,Wipro,Infosys,Capgemini,HCL',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 50000, closingRank: 150000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 70000, closingRank: 190000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 90000, closingRank: 230000 },
    ],
  },
  {
    name: 'Kalinga Institute of Industrial Technology',
    city: 'Bhubaneswar',
    state: 'Odisha',
    type: 'Deemed',
    nirfRank: 46,
    nirfScore: 26.71,
    fees: 250000,
    rating: 3.8,
    established: 1992,
    description: 'KIIT School of Technology with focus on IT and engineering education.',
    website: 'https://ksom.ac.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 350, fees: 250000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 200, fees: 250000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 150, fees: 250000 },
    ],
    placement: {
      avgPackage: 6,
      highestPackage: 24,
      placementPercent: 66,
      topRecruiters: 'TCS,Infosys,Wipro,Accenture,IBM',
    },
    predictorData: [
      { exam: 'JEE_MAIN', category: 'GENERAL', openingRank: 40000, closingRank: 120000 },
      { exam: 'JEE_MAIN', category: 'OBC', openingRank: 58000, closingRank: 155000 },
      { exam: 'JEE_MAIN', category: 'SC', openingRank: 75000, closingRank: 190000 },
    ],
  },
  {
    name: 'Presidency University Bangalore',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'Private',
    nirfRank: 47,
    nirfScore: 25.62,
    fees: 230000,
    rating: 3.6,
    established: 2013,
    description: 'Private university in Bangalore offering modern engineering and tech programs.',
    website: 'https://presidencyuniversity.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 250, fees: 230000 },
      { name: 'B.Tech Data Science', duration: 4, seats: 120, fees: 230000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 100, fees: 230000 },
    ],
    placement: {
      avgPackage: 5,
      highestPackage: 18,
      placementPercent: 62,
      topRecruiters: 'TCS,Wipro,Infosys,HCL,Mindtree',
    },
    predictorData: [
      { exam: 'KCET', category: 'GENERAL', openingRank: 30000, closingRank: 90000 },
      { exam: 'KCET', category: 'OBC', openingRank: 45000, closingRank: 120000 },
      { exam: 'KCET', category: 'SC', openingRank: 60000, closingRank: 150000 },
    ],
  },
  {
    name: 'RV College of Engineering Bangalore',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'Private',
    nirfRank: 48,
    nirfScore: 24.81,
    fees: 200000,
    rating: 4.0,
    established: 1963,
    description: 'Prestigious autonomous college in Bangalore affiliated to VTU with great placements.',
    website: 'https://www.rvce.edu.in',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 180, fees: 200000 },
      { name: 'B.Tech Information Science', duration: 4, seats: 120, fees: 200000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 120, fees: 200000 },
    ],
    placement: {
      avgPackage: 7,
      highestPackage: 28,
      placementPercent: 76,
      topRecruiters: 'Infosys,Wipro,Accenture,TCS,Mindtree',
    },
    predictorData: [
      { exam: 'KCET', category: 'GENERAL', openingRank: 1000, closingRank: 8000 },
      { exam: 'KCET', category: 'OBC', openingRank: 3000, closingRank: 14000 },
      { exam: 'KCET', category: 'SC', openingRank: 6000, closingRank: 22000 },
    ],
  },
  {
    name: 'MS Ramaiah Institute of Technology',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'Private',
    nirfRank: 49,
    nirfScore: 23.94,
    fees: 190000,
    rating: 3.9,
    established: 1962,
    description: 'Well-established autonomous engineering college in Bangalore with strong alumni.',
    website: 'https://www.msrit.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 160, fees: 190000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 130, fees: 190000 },
      { name: 'B.Tech Electrical Engineering', duration: 4, seats: 100, fees: 190000 },
    ],
    placement: {
      avgPackage: 6,
      highestPackage: 24,
      placementPercent: 73,
      topRecruiters: 'Infosys,Wipro,TCS,IBM,Accenture',
    },
    predictorData: [
      { exam: 'KCET', category: 'GENERAL', openingRank: 2000, closingRank: 10000 },
      { exam: 'KCET', category: 'OBC', openingRank: 5000, closingRank: 18000 },
      { exam: 'KCET', category: 'SC', openingRank: 8000, closingRank: 26000 },
    ],
  },
  {
    name: 'PES University Bangalore',
    city: 'Bangalore',
    state: 'Karnataka',
    type: 'Deemed',
    nirfRank: 50,
    nirfScore: 23.12,
    fees: 260000,
    rating: 4.0,
    established: 1988,
    description: 'Reputed deemed university in Bangalore with excellent CS and engineering programs.',
    website: 'https://www.pes.edu',
    field: 'Engineering',
    courses: [
      { name: 'B.Tech Computer Science', duration: 4, seats: 200, fees: 260000 },
      { name: 'B.Tech Electronics Engineering', duration: 4, seats: 150, fees: 260000 },
      { name: 'B.Tech Mechanical Engineering', duration: 4, seats: 100, fees: 260000 },
    ],
    placement: {
      avgPackage: 7,
      highestPackage: 28,
      placementPercent: 77,
      topRecruiters: 'Amazon,Flipkart,Infosys,Oracle,Cisco',
    },
    predictorData: [
      { exam: 'KCET', category: 'GENERAL', openingRank: 500, closingRank: 5000 },
      { exam: 'KCET', category: 'OBC', openingRank: 2000, closingRank: 10000 },
      { exam: 'KCET', category: 'SC', openingRank: 4000, closingRank: 16000 },
    ],
  },
]

async function main() {
  console.log('Seeding database with 50 colleges...')

  await prisma.predictorData.deleteMany()
  await prisma.placement.deleteMany()
  await prisma.course.deleteMany()
  await prisma.review.deleteMany()
  await prisma.savedCollege.deleteMany()
  await prisma.college.deleteMany()

  for (const data of colleges) {
    const { courses, placement, predictorData, ...collegeData } = data

    const college = await prisma.college.create({
      data: {
        ...collegeData,
        courses: {
          create: courses,
        },
        placements: {
          create: {
            ...placement,
            year: 2024,
          },
        },
        predictorData: {
          create: predictorData.map((pd) => ({ ...pd, year: 2024 })),
        },
      },
    })

    console.log(`Created: ${college.name} (ID: ${college.id})`)
  }

  console.log(`\nSeeding complete! Created ${colleges.length} colleges.`)
}

main()
  .catch((e) => {
    console.error('Seed error:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
    await pool.end()
  })
